packages:
  - apps/*
  - packages/*/*

catalog:
  '@biomejs/biome': 2.5.0
  '@cucumber/cucumber': 11.2.0
  '@fontsource/inter': 5.2.8
  '@fontsource/manrope': 5.2.8
  '@headlessui/vue': 1.7.23
  '@nx/js': 23.0.0
  '@nx/vite': 23.0.0
  '@nx/vue': 23.0.0
  '@nx/web': 23.0.0
  '@stryker-mutator/core': 9.6.1
  '@stryker-mutator/vitest-runner': 9.6.1
  '@swc/helpers': 0.5.17
  '@tailwindcss/vite': 4.3.2
  '@tanstack/store': ^0.11.0
  '@tanstack/vue-store': ^0.11.0
  '@types/axios': 0.14.4
  '@types/node': 24.0.15
  '@vitejs/plugin-vue': 6.0.1
  '@vue/test-utils': 2.4.6
  axios: 1.18.1
  class-variance-authority: 0.7.1
  dependency-cruiser: 18.0.0
  esbuild: 0.25.9
  inversify: 8.1.1
  jiti: 2.4.2
  keycloak-js: 26.2.4
  lucide-vue-next: 1.0.0
  msw: 2.14.6
  nx: 23.0.0
  rxjs: 7.8.2
  tailwind-merge: 3.6.0
  tailwindcss: 4.3.1
  tslib: 2.8.1
  tsx: 4.20.5
  typescript: 5.9.2
  vee-validate: 4.15.1
  vite: 8.0.0
  vitest: 4.1.9
  vue: 3.5.22
  vue-router: 4.5.1
  vue-tsc: 2.2.12
