name: Integration

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: corepack enable

      - run: pnpm install --frozen-lockfile

      - run: pnpm nx affected --target=test:unit --base=origin/main --head=HEAD

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: corepack enable

      - run: pnpm install --frozen-lockfile

      - run: pnpm nx affected --target=test:integration --base=origin/main --head=HEAD

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: corepack enable

      - run: pnpm install --frozen-lockfile

      - run: pnpm nx affected --target=lint --base=origin/main --head=HEAD

  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: corepack enable

      - run: pnpm install --frozen-lockfile

      - run: pnpm nx run acceptance-tests:run
