name: Integration

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node-project
      - run: pnpm nx build frontend

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node-project
      - run: pnpm nx run-many --target=typecheck

  acceptance-tests:
    name: Acceptance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node-project
      - run: pnpm nx start acceptance-tests

  domain-tests:
    name: Domain unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node-project
      - run: pnpm nx run-many --target=test --projects=tag:layer:domain

  infrastructure-tests:
    name: Infrastructure integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node-project
      - run: pnpm nx run-many --target=test --projects=tag:layer:infrastructure

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node-project
      - run: pnpm run lint
